volumes:
  kittygram_pg_data:
  static_volume:
  media_volume:

networks:
  kittygram-network:
    driver: bridge

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data
    networks:
      - kittygram-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kittygram_app -d kittygram_production"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend:
    image: oeowla/kittygram_backend-1:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/mediafiles
    networks:
      - kittygram-network
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    image: oeowla/kittygram_frontend-1:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
    networks:
      - kittygram-network
  
  gateway:
    image: oeowla/kittygram_gateway-1:latest
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/mediafiles
    ports:
      - "9000:80"
    networks:
      - kittygram-network
    depends_on:
      - backend
